#!/bin/sh
set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
    update-alternatives --install /usr/bin/x-www-browser \
        x-www-browser /opt/SimpleBrowser/simple 80
    chown root /opt/SimpleBrowser/chrome-sandbox
    chmod 4755 /opt/SimpleBrowser/chrome-sandbox
    echo "Run sudo xdg-settings set default-web-browser min.desktop && sudo update-alternatives --config x-www-browser to set Min as your default browser."
    ln -s /opt/SimpleBrowser/simple /usr/bin/simple
fi
